import streamlit as st
def home():

    # Home page title
    st.markdown(
        """
        <div style="background-color: rgba(0,0,0,0.6); padding: 20px;">
            <h1 style="font-size: 60px;color: #1fddff;"> <b> Plastic Mapper : Uncover the Plastic Pollution </b> </h1>
        <div>
        """,
        unsafe_allow_html=True
    )
    # Introduction section
    st.markdown(
        """
        <div style="background-color: rgba(0,0,0,0.6); padding: 20px ;">
            <h1 style="font-size: 40px; color :#bbeff2;">Are you concerned about plastic pollution and its impact on the environment?</h1>
        <div>
        """,
        unsafe_allow_html=True
    )

    st.markdown(
        """
        <div style="background-color: rgba(0,0,0,0.6); padding: 20px;">
            <p style="font-size: 20px;">PlasticMapper is your powerful ally in the fight against plastic pollution, empowering you to make a positive impact on the environment. With our advanced drone image analysis, you can explore plastic hotspots, uncover hidden patterns, and take informed actions to create a cleaner and sustainable planet. Together, let's drive change and protect our precious ecosystems from the harmful effects of plastic waste. Join PlasticMapper today and be a part of the solution for a better tomorrow!</p>
        <div>
        """,
        unsafe_allow_html=True
    )

    # What is PlasticMapper section
    st.markdown(
        """
        <div style="background-color: rgba(0,0,0,0.6); padding: 20px; color: #6fe36d;">
            <h2 style="font-size: 30px; color: #bbeff2;">What is PlasticMapper?</h2>
        <div>
        """,
        unsafe_allow_html=True
    )

    st.markdown(
        """
        <div style="background-color: rgba(0,0,0,0.6); padding: 20px;">
            <p style="font-size: 20px;">
PlasticMapper is a cutting-edge web application designed to tackle the pressing issue of plastic pollution. By utilizing drone images, users can gain valuable insights into the distribution of plastic waste on an interactive map. The platform offers a range of features, including visualizing plastic hotspots, providing insightful statistics, and showcasing the reliability of plastic detection through confidence score distribution generated by our AI model.</p>
        <div>
        """,
        unsafe_allow_html=True
    )

    # Key Features section
    st.markdown(
        """
        <div style="background-color: rgba(0,0,0,0.6); padding: 20px; color: #6fe36d;">
            <h2 style="font-size: 30px; color: #bbeff2;">Key Features:</h2>
        <div>
        """,
        unsafe_allow_html=True
    )

    st.markdown(
        """
        <div style="background-color: rgba(0,0,0,0.6); padding: 20px;">
            <ol>
                 <li style="font-size: 20px;">Visualize Plastic Hotspots: Explore detailed maps displaying the concentration of plastic waste in different regions.</li>
                 <li style="font-size: 20px;">Insightful Statistics: Get valuable statistics, such as the total number of plastics detected and the average plastic density.</li>
                 <li style="font-size: 20px;">Detection Confidence: Understand the reliability of plastic detection with confidence score distribution generated by our AI model.</li>
            </ol>
        <div>
        """,
        unsafe_allow_html=True
    )

    # Get Started section
    st.markdown(
        """
        <div style="background-color: rgba(0,0,0,0.6); padding: 20px; color: #6fe36d;">
            <h2 style="font-size: 30px; color: #bbeff2;">Get Started:</h2>
        <div>
        """,
        unsafe_allow_html=True
    )

    st.markdown(
        """
        <div style="background-color: rgba(0,0,0,0.6); padding: 20px;">
            <ol>
                 <li style="font-size: 20px;">Detect Plastic: Head to the <span style="color:#1fddff">Detect</span> page to upload your drone images for plastic detection.</li>
                 <li style="font-size: 20px;">Insights: Check out the <span style="color:#1fddff">Insights</span> page to view the visualizations and statistics related to plastic distribution.</li>
                 <li style="font-size: 20px;">Plastic Details: Explore individual images, annotated with detected plastics and geolocation information.</li>
             </ol>
        <div>
        """,
        unsafe_allow_html=True
    )

    # Final message
    st.markdown(
        """
        <div style="background-color: rgba(0,0,0,0.6); padding: 20px;">
            <p style="font-size: 20px;">Join the Fight Against Plastic Pollution! Start Mapping Now!</p>
        <div>
        """,
        unsafe_allow_html=True
    )

    st.write("")
    st.write("")
    st.write("")
    st.video("https://www.youtube.com/watch?v=0EyaTqezSzs&t=67s")

